apiVersion: v1
kind: Service
metadata:
  labels:
    app: reunion-frontend
  name: reunion-frontend-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: reunion-frontend
  sessionAffinity: None
  type: ClusterIP